// <auto-generated />
using System;
using FridgeApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FridgeApi.DAL.Migrations
{
    [DbContext(typeof(FridgeContext))]
    [Migration("20221206120145_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FridgeApi.DAL.Models.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Fridge");
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.FridgeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fridge_Model");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29bda128-3d64-4882-a9f4-c42a089dcca9"),
                            Name = "Atlanta",
                            Year = 1998
                        },
                        new
                        {
                            Id = new Guid("c4f34e6d-2db9-4d22-aa03-d5940d5e73c5"),
                            Name = "Horizon",
                            Year = 1993
                        },
                        new
                        {
                            Id = new Guid("dace556c-2d59-490e-984e-8800b7a314b9"),
                            Name = "LG",
                            Year = 2001
                        },
                        new
                        {
                            Id = new Guid("0d540ebf-90c4-492d-839c-7a87a4a2e63f"),
                            Name = "Philips",
                            Year = 2000
                        },
                        new
                        {
                            Id = new Guid("740dd9cb-bf97-4d9d-bd61-272da57b118b"),
                            Name = "AtlantaPanasonic",
                            Year = 2003
                        });
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.FridgeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ProductId");

                    b.ToTable("Fridge_Products");
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DefaultQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b8ce319-3059-4638-b910-2c4120c4882f"),
                            DefaultQuantity = 6,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = new Guid("56e96036-8a30-4b97-92e4-ab3871d39f13"),
                            DefaultQuantity = 1,
                            Name = "Grape"
                        },
                        new
                        {
                            Id = new Guid("e97a9683-bb43-4883-91ac-ca92f2d26aca"),
                            DefaultQuantity = 3,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("5d449b4d-5fc5-4506-920f-f1c8f9bc5255"),
                            DefaultQuantity = 1,
                            Name = "Beaf"
                        },
                        new
                        {
                            Id = new Guid("b46b5037-6193-492d-8a03-05c9663cccc1"),
                            DefaultQuantity = 8,
                            Name = "Cherry"
                        },
                        new
                        {
                            Id = new Guid("60f69028-66af-47cd-91dd-4258cd6f3ec8"),
                            DefaultQuantity = 4,
                            Name = "Fish"
                        });
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.Fridge", b =>
                {
                    b.HasOne("FridgeApi.DAL.Models.FridgeModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.FridgeProduct", b =>
                {
                    b.HasOne("FridgeApi.DAL.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeApi.DAL.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
