// <auto-generated />
using System;
using FridgeApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FridgeApi.DAL.Migrations
{
    [DbContext(typeof(FridgeContext))]
    [Migration("20221211110508_Accounts")]
    partial class Accounts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FridgeApi.DAL.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Fridge");
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.FridgeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fridge_Model");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53e8a62f-aa96-48c5-b573-96810bc5a62c"),
                            Name = "Atlanta",
                            Year = 1998
                        },
                        new
                        {
                            Id = new Guid("856d26bc-4f2e-4e3f-b548-9b5b111f3f90"),
                            Name = "Horizon",
                            Year = 1993
                        },
                        new
                        {
                            Id = new Guid("1a343814-0132-41d0-ab0a-312d9dfb1dc1"),
                            Name = "LG",
                            Year = 2001
                        },
                        new
                        {
                            Id = new Guid("8e9b2c63-ccdd-4ad2-b576-a89019c4ac44"),
                            Name = "Philips",
                            Year = 2000
                        },
                        new
                        {
                            Id = new Guid("ed48d712-7ba8-49f4-8d57-cee37a18b07b"),
                            Name = "Panasonic",
                            Year = 2003
                        });
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.FridgeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ProductId");

                    b.ToTable("Fridge_Products");
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DefaultQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("834cefb2-7b88-43ec-8813-f169a1cf29ba"),
                            DefaultQuantity = 6,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = new Guid("3c02d828-1bbc-449f-a582-a760667b8a4e"),
                            DefaultQuantity = 1,
                            Name = "Grape"
                        },
                        new
                        {
                            Id = new Guid("7efe0fee-18a7-4f72-8a53-b84228b5c290"),
                            DefaultQuantity = 3,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("abdf54f0-0f8b-4b2b-bb55-eb11cbf3499c"),
                            DefaultQuantity = 1,
                            Name = "Beaf"
                        },
                        new
                        {
                            Id = new Guid("17eb2108-9509-4f5f-b7ac-f669a8cb5547"),
                            DefaultQuantity = 8,
                            Name = "Cherry"
                        },
                        new
                        {
                            Id = new Guid("3aaf9c9e-724a-4ad1-ae81-ad6ef9483ad5"),
                            DefaultQuantity = 4,
                            Name = "Fish"
                        });
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.Fridge", b =>
                {
                    b.HasOne("FridgeApi.DAL.Models.FridgeModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("FridgeApi.DAL.Models.FridgeProduct", b =>
                {
                    b.HasOne("FridgeApi.DAL.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeApi.DAL.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
